{"name": "登录异常，测试数据是:{'accounts': '', 'pwd': 'yaoyao', 'exp': '登录账号有误'}", "status": "passed", "description": "\n        对登录接口进行异常登录的测试\n        :param args: 参数化的数据\n        :return:\n        ", "attachments": [{"name": "log", "source": "feff1851-0f98-4750-b1b7-c5f592c2a117-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "args", "value": "{'accounts': '', 'pwd': 'yaoyao', 'exp': '登录账号有误'}"}], "start": 1634269421358, "stop": 1634269421481, "uuid": "e33ed2f6-db41-4abd-a0ca-8a561d6bf31d", "historyId": "ff1d27090ef74452512974d50f385b0f", "testCaseId": "acfd50c72596b11b4392c40d7652bccf", "fullName": "script.test_login.TestLogin#test_login_error", "labels": [{"name": "story", "value": "异常数据的登录接口测试"}, {"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-95KM4O2I"}, {"name": "thread", "value": "32616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_login"}]}